## sroos_interns
credentials:
  consumer_key:    OAk1jpqljfvceUhWn1KBcQ
  consumer_secret: VFrbCrmBUjiOSFmo2pGFaemu90BfL0lBilSoagv3A
  token:           191654181-bDKADVbv6nhJf4jeZZysZnVDsMHvg7GaNKN32iWw
  secret:          VG0dZJPgb7uptd29p3u6pFTAydgAzmLUpMDiHC3aI
settings:
  friend_id:          19729328
  friend_screen_name: ramangulati
